//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public int IdDireccion { get; set; }
        public string Nombre { get; set; }
        public string Calle { get; set; }
        public string CodigoPais { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
